spring.application.name=dingdingDemo
spring.datasource.url=jdbc:mysql://192.168.100.125:3306/ding_db
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
server.port=8083
#server.port=8084

dingtalk.appkey=dingp6bncaeosol6um2o
dingtalk.appsecret=Pll8E9lpv_3HzQoFXjhfDI9ImWDl29C1gtkTJY58wFI_qrQHaKy619UD5qfjnbIk
dingtalk.userid=02186700545626304822
#dingtalk.userid=yida_pub_account
#??yida_pub_account???????????
dingtalk.size=300


# MyBatis-Plus??
mybatis-plus.mapper-locations=classpath:mapper/*.xml
mybatis-plus.type-aliases-package=com.quanhai.dingdingdemo.model
mybatis-plus.configuration.map-underscore-to-camel-case=true

spring.data.redis.host=192.168.100.125
spring.data.redis.port=6379

# slf4j????
logging.config=classpath:logback.xml

#mymail.user=3123544976@qq.com
#mymail.pwd=myufgudfdkfjdejf
#mymail.to=3123544976@qq.com
#mymail.smtp=smtp.qq.com
#mymail.port=465
#mymail.badTo=3123544976@qq.com



mymail.user=jiayang.zhao@quanhaikj.cn
mymail.pwd=LbHUuNHScbd13K74
mymail.to=3123544976@qq.com
mymail.badTo=3123544976@qq.com
mymail.smtp=smtphz.qiye.163.com
mymail.port=465
