spring.application.name=dingdingDemo
spring.datasource.url=jdbc:mysql://localhost:3306/ding_db
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
server.port=8083

dingtalk.appkey=dingp6bncaeosol6um2o
dingtalk.appsecret=Pll8E9lpv_3HzQoFXjhfDI9ImWDl29C1gtkTJY58wFI_qrQHaKy619UD5qfjnbIk
dingtalk.userid=02186700545626304822
dingtalk.size=300


# MyBatis-Plus??
mybatis-plus.mapper-locations=classpath:mapper/*.xml
mybatis-plus.type-aliases-package=com.quanhai.dingdingdemo.model
spring.data.redis.host=localhost
spring.data.redis.port=6379